"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 3.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os.path
from pathlib import Path
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
import account.apps

BASE_DIR = Path(__file__).resolve().parent.parent

LOGIN_REDIRECT_URL = "home"
# با استفاده از این خط کد میتوانیم به سیستم بفهمانیم که بعد از لاگین کردن به کدام صفحه حرکت کن
LOGIN_URL = 'login'
# اگر بخواهیم بعد از لاگ اوت کردن وارد لاگین شود از این قطعه کد استفاده میکنیم
LOGOUT_REDIRECT_URL = 'login'


# با استفاده ازاین خط کد میتوانیم به سیستم بفهمانیم که اگر از لاگین ،لاگ اوت کردیم دیگر با رفرش دکردن صفحه ی home  ما را به صفحه ی لاگین باز گرداند
# یورال صفحه ای که میخواهیم بعد لاگین وارد آن شویم را در این قسمت مشخص میکنیم
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
#  'django-insecure-i7r9a*01s$c&2omp2dt+s7@_hq6o0k2zng57$z5jc-u(#m+-1j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
# [127.0.0.1:8000']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog.apps.BlogConfig',
    'extensions',
    'account.apps.AccountConfig',
    'widget_tweaks',
    'crispy_forms',
    'django_gravatar',
    'comment',
    'star_ratings',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'blog.middleware.SaveIPAddressMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [ BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa-ir'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#برای ایجاد فایل های سی اس اس پنل ادمین برای تغییرات صفحات از این راه استفاده میکنیم کخ در سایت خود جنگو مربوط به static files in django می باشد
STATICFILES_DIRS = [
    BASE_DIR / "static"
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# BASE_DIR / "media"  # os.path.join(BASE_DIR, 'media')
# o BASE_DIR / "media"
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/s ettings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CRISPY_TEMPLATE_PACK = 'bootstrap4'
# اگر غالب استفاده شده بوتسرترپ پنج بود تغییر میدیم
AUTH_USER_MODEL = 'account.User'

# ارسال ایمیل در کنسول
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_USE_TLS = True
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

# اندازه ی ستاره ها
STAR_RATINGS_STAR_HEIGHT = 16
#  تعداد ستاره ها
# STAR_RATINGS_RANGE  = 7
# اجازه بدیم کسانی هم که در سایت لاگین نکرده اند هم رای بدن
# STAR_RATINGS_ANONYMOUS = True
# اجازه بدیم که رای خودش را تغییر بده
# STAR_RATINGS_RERATE = False
# اگر بخواهیم شکل را عوض کنیم
# STAR_RATINGS_STAR_SPRITE=os.path.join(BASE_DIR, 'media'